spring:
    # https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    datasource:
        dynamic:
          patterns: com.zhongxiaohua.samples.dao.*
        username: root
        password: root_hua123
        druid:
          initial-size: 2
          min-idle: 2
          max-active: 20
          # 配置获取连接等待超时的时间
          max-wait: 6000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          min-evictable-idle-time-millis: 300000
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          time-between-eviction-runs-millis: 60000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          # 打开PSCache，并且指定每个连接上PSCache的大小
          pool-prepared-statements: true
          max-open-prepared-statements: 20
          max-pool-prepared-statement-per-connection-size: 20
          connection-properties: druid.stat.slowSqlMillis=5000
          # 合并多个DruidDataSource的监控数据
          use-global-data-source-stat: true
          # 配置监控统计拦截的filters
          filters: stat
          connection-init-sqls: set names utf8mb4;
          # 配置多数据源
          master:
            url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&noDatetimeStringSync=true&zeroDateTimeBehavior=convertToNull
          slave:
            url: jdbc:mysql://127.0.0.1:3306/demo_slave?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&noDatetimeStringSync=true&zeroDateTimeBehavior=convertToNull

# http://www.mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/
mybatis:
  type-aliases-package: com.zhongxiaohua.samples.dao
  mapper-locations: classpath:/mybatis/*.xml
  configuration:
    #使全局的映射器启用或禁用缓存
    cache-enabled: true
    #全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载
    lazy-loading-enabled: true
    #当启用时，有延迟加载属性的对象在被调用时将会完全加载任意属性。否则，每种属性将会按需要加载。
    aggressive-lazy-loading: true
    #是否允许单条sql 返回多个数据集  (取决于驱动的兼容性) default:true
    multiple-result-sets-enabled: true
    #是否可以使用列的别名 (取决于驱动的兼容性) default:true
    use-column-label: true
    #允许JDBC 生成主键。需要驱动器支持。如果设为了true，这个设置将强制使用被生成的主键，有一些驱动器不兼容不过仍然可以执行。  default:false
    use-generated-keys: true
    #指定 MyBatis 如何自动映射 数据基表的列 NONE：不隐射　PARTIAL:部分  FULL:全部
    auto-mapping-behavior: "PARTIAL"
    #这是默认的执行类型  （SIMPLE: 简单； REUSE: 执行器可能重复使用prepared statements语句；BATCH: 执行器可以重复执行语句和批量更新）
    default-executor-type: "SIMPLE"
    #使用驼峰命名法转换字段。
    map-underscore-to-camel-case: true
    #设置本地缓存范围 session:就会有数据的共享  statement:语句范围 (这样就不会有数据的共享 ) defalut:session
    local-cache-scope: "SESSION"
    #设置但JDBC类型为空时,某些驱动程序 要指定值,default:OTHER，插入空值时不需要指定类型
    jdbc-type-for-null: "NULL"

logging:
  level:
   com.zhongxiaohua: debug
